package com.zfg.test.common;

/**
 * Created by zfg on 2018/6/12
 */
public class Contants {
    public static final String START_AROUTER_ACTIVITY="/test/ArouterTestActivity";
    public static final String gson=" [{\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 1473,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A1\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2934,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A2\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 1474,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A3\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2542,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A4\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"敞篷轿车\",\n" +
            "\t\t\"modelid\": 1475,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A3\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿跑车\",\n" +
            "\t\t\"modelid\": 1479,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A5\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"掀背轿跑车\",\n" +
            "\t\t\"modelid\": 1481,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A5\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"旅行车\",\n" +
            "\t\t\"modelid\": 1482,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A6\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"掀背轿跑车\",\n" +
            "\t\t\"modelid\": 1484,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A7\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿跑车\",\n" +
            "\t\t\"modelid\": 1515,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"TT\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 1483,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A6\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"敞篷轿跑车\",\n" +
            "\t\t\"modelid\": 1516,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"TT\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"敞篷轿车\",\n" +
            "\t\t\"modelid\": 2956,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A4\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"旅行车\",\n" +
            "\t\t\"modelid\": 2933,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"80\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"旅行车\",\n" +
            "\t\t\"modelid\": 1476,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A4\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"敞篷轿跑车\",\n" +
            "\t\t\"modelid\": 1480,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A5\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 1486,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A8\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"SUV\",\n" +
            "\t\t\"modelid\": 1506,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"Q3\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"SUV\",\n" +
            "\t\t\"modelid\": 1507,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"Q5\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"SUV\",\n" +
            "\t\t\"modelid\": 1508,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"Q7\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2540,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"100\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"旅行车\",\n" +
            "\t\t\"modelid\": 2931,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"100\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2932,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"80\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"掀背跑车\",\n" +
            "\t\t\"modelid\": 1485,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A7\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"跑车\",\n" +
            "\t\t\"modelid\": 1510,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"R8\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"敞篷跑车\",\n" +
            "\t\t\"modelid\": 1509,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"R8\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"敞篷跑车\",\n" +
            "\t\t\"modelid\": 1478,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A5\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 183,\n" +
            "\t\t\"vehicletype\": \"跑车\",\n" +
            "\t\t\"modelid\": 1477,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A5\",\n" +
            "\t\t\"makename\": \"奥迪汽车\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 1474,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A3\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2542,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A4\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"SUV\",\n" +
            "\t\t\"modelid\": 1506,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"Q3\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"SUV\",\n" +
            "\t\t\"modelid\": 3536,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"Q2\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2540,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"100\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 2541,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"200\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"轿车\",\n" +
            "\t\t\"modelid\": 1483,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"A6\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}, {\n" +
            "\t\t\"makeid\": 298,\n" +
            "\t\t\"vehicletype\": \"SUV\",\n" +
            "\t\t\"modelid\": 1507,\n" +
            "\t\t\"modelbrandid\": 256,\n" +
            "\t\t\"model\": \"Q5\",\n" +
            "\t\t\"makename\": \"一汽大众(奥迪)\",\n" +
            "\t\t\"rowid\": 1\n" +
            "\t}]";
}
